# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

include Makefile-common

# Check that Argo CD (OpenShift GitOps) is present; install if missing (must run before pattern install)
.PHONY: check-argocd
check-argocd: ## Verify Argo CD (GitOps Operator) is installed; install it if not present
	@./scripts/check-or-install-argocd.sh

# OpenShift AI is created by this pattern via GitOps (values-prod subscriptions); run AFTER Argo has synced.
.PHONY: check-openshift-ai-operators
check-openshift-ai-operators: ## Verify OpenShift AI 3.x (rhods-operator) subscription exists and CSV is Succeeded
	@./scripts/check-openshift-ai-operators.sh

# Same as install but requires OpenShift AI already installed (e.g. manual install before GitOps)
.PHONY: install-with-openshift-ai-precheck
install-with-openshift-ai-precheck: check-argocd check-cert-manager check-openshift-ai-operators argocd-ignore-operator-subscriptions-optional pattern-install
	-@./scripts/argocd-ignore-existing-operator-subscriptions.sh || echo >&2 ">>> Run: make argocd-ignore-operator-subscriptions"

# Block community cert-manager / duplicate RH cert-manager before GitOps applies operators
.PHONY: check-cert-manager
check-cert-manager: ## Cert-manager preflight (set CERTMANAGER_AVOID_SUBSCRIPTION_RECONCILE=1 to guard existing RH operator)
	@./scripts/check-cert-manager-cluster.sh

# Patch hub Argo Application so existing OLM Subscriptions are not overwritten from Git
.PHONY: argocd-ignore-operator-subscriptions
argocd-ignore-operator-subscriptions: ## Add ignoreDifferences for all operators.coreos.com/Subscription (see docs/ARGO-OPERATORS-NO-OVERWRITE.md)
	@chmod +x ./scripts/argocd-ignore-existing-operator-subscriptions.sh 2>/dev/null; ./scripts/argocd-ignore-existing-operator-subscriptions.sh

.PHONY: argocd-ignore-operator-subscriptions-optional
argocd-ignore-operator-subscriptions-optional:
	@chmod +x ./scripts/argocd-ignore-existing-operator-subscriptions.sh 2>/dev/null; ./scripts/argocd-ignore-existing-operator-subscriptions.sh || true

# ---------------------------------------------------------------------------
# install — MUST stay last so it overrides Makefile-common's "install: pattern-install".
# Do not add check-openshift-ai-operators here; rhods is created by GitOps after sync.
# ---------------------------------------------------------------------------
.PHONY: _rag_llm_sno_install
_rag_llm_sno_install: check-argocd check-cert-manager argocd-ignore-operator-subscriptions-optional pattern-install
	-@./scripts/argocd-ignore-existing-operator-subscriptions.sh || echo >&2 ">>> make argocd-ignore-operator-subscriptions (see docs/ARGO-OPERATORS-NO-OVERWRITE.md)"

.PHONY: install
install: _rag_llm_sno_install ## Installs pattern (Argo CD + cert preflight + pattern-install); verify rhoai after sync
