clusterGroup:
  name: prod

  namespaces:
    - rag-llm-sno
    - openshift-nfd
    - nvidia-gpu-operator
    - cert-manager
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - openshift-serverless:
        operatorGroup: true
        targetNamespaces: []
    - openshift-storage:
        operatorGroup: true
        targetNamespaces:
          - openshift-storage
    - openshift-pipelines
    - redhat-ods-applications
    - rhoai-model-registries
    - rhods-notebooks

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      source: certified-operators
    serverless:
      name: serverless-operator
      namespace: openshift-serverless
    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: fast-3.x  # OpenShift AI 3.x; use stable-3.x when available for production
    certmanager:
      name: cert-manager
      namespace: cert-manager
      source: redhat-operators
    lvms:
      name: lvms-operator
      namespace: openshift-storage

  applications:
    nfd:
      name: nfd
      namespace: openshift-nfd
      path: charts/nfd

    nvidia-config:
      name: nvidia-config
      namespace: nvidia-gpu-operator
      path: charts/nvidia-config

    lvms:
      name: lvms
      namespace: openshift-storage
      path: charts/lvms

    dsc:
      name: dsc
      namespace: rag-llm-sno
      path: charts/dsc

    granite-inference-service:
      name: granite-inference-service
      namespace: rag-llm-sno
      path: charts/vllm-inference-service
      extraValueFiles:
        - $patternref/overrides/granite-inference-service-values.yaml

    gpt-oss-inference-service:
      name: gpt-oss-inference-service
      namespace: rag-llm-sno
      path: charts/vllm-inference-service
      extraValueFiles:
        - $patternref/overrides/gpt-oss-inference-service-values.yaml

    gemma2-inference-service:
      name: gemma2-inference-service
      namespace: rag-llm-sno
      path: charts/vllm-inference-service
      extraValueFiles:
        - $patternref/overrides/gemma2-inference-service-values.yaml

    llamastack:
      name: llamastack
      namespace: rag-llm-sno
      path: charts/llamastack

    rag-llm-frontend:
      name: rag-llm-frontend
      namespace: rag-llm-sno
      repoURL: https://github.com/validatedpatterns-sandbox/rag-llm-demo-ui
      chartVersion: main
      path: helm
      extraValueFiles:
        - $patternref/overrides/rag-llm-frontend-values.yaml

    openwebui:
      name: openwebui
      namespace: rag-llm-sno
      repoURL: https://github.com/open-webui/helm-charts
      chartVersion: main
      path: charts/open-webui
      extraValueFiles:
        - $patternref/overrides/openwebui-values.yaml
